version: '2'
services:
#  php:
#    image: yiisoftware/yii2-php:8.2-apache
#    volumes:
#      - ~/.composer-docker/cache:/root/.composer/cache:delegated
#      - ./:/app:delegated
#    ports:
#      - '8000:80'
#    networks:
#      - default
#    depends_on:
#      - mysql
#      - redis
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2-php
    volumes:
      - .:/var/www
    expose:
      - "9000"
    depends_on:
      - mysql
      - redis

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: yii2_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - php-fpm

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shorturldb
      MYSQL_USER: shorturluser
      MYSQL_PASSWORD: password
      MYSQL_INITDB_SKIP_TZINFO: 1
      TZ: UTC
    command: --log-bin-trust-function-creators=1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - default

volumes:
  db_data:
  redis_data:

networks:
  default:
    driver: bridge